development:
  adapter: mysql
  database: orderfrozenseafood_development
  username: root
  password: 
  host: localhost
  
test:
  adapter: mysql
  database: orderfrozenseafood_test
  username: root
  password: 
  host: localhost
